### ISSUE TITLE
Not work on Vue

### ISSUE THREAD

**Issue by shayelbaz1** [ph1p/vue-paintable#10]

**Comment by ph1p** [comment]
Hi @shayelbaz1 ! Thanks for reporting. Could you please tell me which version of Vue you are using? I have wanted to rewrite it for a long time anyway, then I can look at it immediately (:

**Comment by ph1p** [comment]
Hi @shayelbaz1,
Maybe you can try it again with the new paintable I'm writing currently: https://github.com/ph1p/paintable-vue
It is currently under heavy development (:
I close this for now. Feel always free to reopen it.
