### ISSUE TITLE
Conflicting with app

### ISSUE THREAD

**Issue by afrasiyabhaider** [ph1p/vue-paintable#17]
I am using latest version of vue-paintable in Laravel vues. But its conflicting with other dependencies. Shockingly its not throwing error/exception or anything so I can resolve it. My whole app is blank after using it. When I remove its import app works fine. When i checked in vue cosole tools in chrome. All of my components are there but the screen was blank. This all happened after import of vue-paintable. Please tell me how to resolve this issue @ph1p @jsproede @Blackfaded

**Comment by ph1p** [comment]
Hi @afrasiyabhaider
Thanks for the report. I am in the process of rewriting the whole package. I will let you know as soon as I update the package. 
It would be very helpful if you share a minimal example of your code.

**Comment by ph1p** [comment]
Hi @afrasiyabhaider,
As I said, I'm currently rewriting the plugin. 
You can take a look at these two new Repos (currently under heavy development):

- Core: https://github.com/ph1p/paintable-core
- Vue: https://github.com/ph1p/paintable-vue
